# Generated by Django 4.1.2 on 2022-10-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('habito', models.CharField(max_length=20, verbose_name='Hábito')),
                ('donde', models.CharField(max_length=20, verbose_name='Dónde')),
                ('cantidad', models.CharField(max_length=20, verbose_name='Cantidad')),
            ],
        ),
    ]
